services:
  pieceofcake.webapi:
    image: ${DOCKER_REGISTRY-}pieceofcakewebapi
    build:
      context: .
      dockerfile: PieceOfCake.WebApi/Dockerfile
    ports:
       - 8080:8080
       - 8081:8081

  pieceofcake.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=Pass1234!
       - MSSQL_PID=Express
    ports:
       - 1433:1433
    volumes:
       - ./sql_data/:/var/opt/mssql/ \